# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Pongsakorn<br>U-chupala"
tagline:          "Pongsakorn U-chupala's profile"
description:      'Ph.D. Student'
url:              https://knightbaron.github.io
baseurl:          /

author:
  name:           'Pongsakorn U-chupala'
  url:            https://knightbaron.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
