# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Pongsakorn U&#8209;chupala"
tagline:          "Pongsakorn U&#8209;chupala's profile"
description:      'Ph.D. Student'
url:              https://knightbaron.github.io
baseurl:          /

author:
  name:           'Pongsakorn U&#8209;chupala'
  url:            https://knightbaron.github.io

paginate:         5

gems:
  - jekyll-sitemap

# Custom
index_title:      Profile  # Used in the sidebar
